name: Maven Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Build with Maven
        run: |
          cd ecommerce-multivendor-backend-master
          mvn clean package

      # Set up Maven settings for Nexus deployment
      - name: Set up Maven settings
        run: |
          mkdir -p ~/.m2
          echo "<settings>
                  <servers>
                    <server>
                      <id>b2c-snapshots</id>
                      <username>admin</username>
                      <password>Shekhar@2301</password>
                    </server>
                  </servers>
                </settings>" > ~/.m2/settings.xml

      # Build and deploy to Nexus
      - name: Build and deploy to Nexus
        run: |
          mvn -B clean deploy --file ecommerce-multivendor-backend-master/pom.xml

      # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_REGISTRY }}/ecommerce-multivendor-backend:latest ecommerce-multivendor-backend-master/

      # Login to Docker registry (Docker Hub or GitHub Container Registry)
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Push Docker image to Docker registry
      - name: Push Docker image to registry
        run: |
          docker push ${{ secrets.DOCKER_REGISTRY }}/ecommerce-multivendor-backend
