name: Maven Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Build with Maven
      run: mvn clean package

    - name: Upload to Nexus
      if: success()
      env:
        NEXUS_URL: ${{ secrets.NEXUS_URL }}
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}
      run: |
        mvn deploy -DaltDeploymentRepository=nexus-releases::default::${{ secrets.NEXUS_URL }}/repository/nexus-releases/

